using System.Runtime.CompilerServices;
using ComponentRouting.Maui;
using ComponentRouting.Maui.Exceptions;
using ComponentRouting.Maui.Extension;
using ComponentRouting.Maui.Ioc;
using ComponentRouting.Maui.Model;
using ComponentRouting.Maui.Model.Core;
using ComponentRouting.Maui.Provider.Core;
using ComponentRouting.Maui.Service.Core;

[assembly: TypeForwardedTo(typeof(AppLifecycleAwareComponent))]
[assembly: TypeForwardedTo(typeof(Component))]
[assembly: TypeForwardedTo(typeof(ComponentFactory))]
[assembly: TypeForwardedTo(typeof(Presenter))]
[assembly: TypeForwardedTo(typeof(RoutableComponent<,>))]
[assembly: TypeForwardedTo(typeof(Router))]
[assembly: TypeForwardedTo(typeof(RouterRuntimeLifecycle))]
[assembly: TypeForwardedTo(typeof(RouterShutdownContext))]
[assembly: TypeForwardedTo(typeof(RouterShutdownOptions))]
[assembly: TypeForwardedTo(typeof(RouterShutdownReason))]
[assembly: TypeForwardedTo(typeof(ComponentError))]
[assembly: TypeForwardedTo(typeof(ComponentException))]
[assembly: TypeForwardedTo(typeof(RouterError))]
[assembly: TypeForwardedTo(typeof(RouterException))]
[assembly: TypeForwardedTo(typeof(ReflectionExtension))]
[assembly: TypeForwardedTo(typeof(ServiceProviderComponentFactory))]
[assembly: TypeForwardedTo(typeof(SafeAreaInsets))]
[assembly: TypeForwardedTo(typeof(LocalizableComponent))]
[assembly: TypeForwardedTo(typeof(LocalizableElement))]
[assembly: TypeForwardedTo(typeof(LocalizableEntity))]
[assembly: TypeForwardedTo(typeof(CatalogProvider))]
[assembly: TypeForwardedTo(typeof(LocaleProvider))]
[assembly: TypeForwardedTo(typeof(SafeAreaInsetsService))]
